// Models.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

protocol JSONEncodable {
    func encodeToJSON() -> Any
}

public enum ErrorResponse : Error {
    case Error(Int, Data?, Error)
}

open class Response<T> {
    open let statusCode: Int
    open let header: [String: String]
    open let body: T?

    public init(statusCode: Int, header: [String: String], body: T?) {
        self.statusCode = statusCode
        self.header = header
        self.body = body
    }

    public convenience init(response: HTTPURLResponse, body: T?) {
        let rawHeader = response.allHeaderFields
        var header = [String:String]()
        for (key, value) in rawHeader {
            header[key as! String] = value as? String
        }
        self.init(statusCode: response.statusCode, header: header, body: body)
    }
}

private var once = Int()
class Decoders {
    static fileprivate var decoders = Dictionary<String, ((AnyObject) -> AnyObject)>()

    static func addDecoder<T>(clazz: T.Type, decoder: @escaping ((AnyObject) -> T)) {
        let key = "\(T.self)"
        decoders[key] = { decoder($0) as AnyObject }
    }

    static func decode<T>(clazz: T.Type, discriminator: String, source: AnyObject) -> T {
        let key = discriminator;
        if let decoder = decoders[key] {
            return decoder(source) as! T
        } else {
            fatalError("Source \(source) is not convertible to type \(clazz): Maybe swagger file is insufficient")
        }
    }

    static func decode<T>(clazz: [T].Type, source: AnyObject) -> [T] {
        let array = source as! [AnyObject]
        return array.map { Decoders.decode(clazz: T.self, source: $0) }
    }

    static func decode<T, Key: Hashable>(clazz: [Key:T].Type, source: AnyObject) -> [Key:T] {
        let sourceDictionary = source as! [Key: AnyObject]
        var dictionary = [Key:T]()
        for (key, value) in sourceDictionary {
            dictionary[key] = Decoders.decode(clazz: T.self, source: value)
        }
        return dictionary
    }

    static func decode<T>(clazz: T.Type, source: AnyObject) -> T {
        initialize()
        if T.self is Int32.Type && source is NSNumber {
            return source.int32Value as! T;
        }
        if T.self is Int64.Type && source is NSNumber {
            return source.int64Value as! T;
        }
        if T.self is UUID.Type && source is String {
            return UUID(uuidString: source as! String) as! T
        }
        if source is T {
            return source as! T
        }
        if T.self is Data.Type && source is String {
            return Data(base64Encoded: source as! String) as! T
        }

        let key = "\(T.self)"
        if let decoder = decoders[key] {
           return decoder(source) as! T
        } else {
            fatalError("Source \(source) is not convertible to type \(clazz): Maybe swagger file is insufficient")
        }
    }

    static func decodeOptional<T>(clazz: T.Type, source: AnyObject?) -> T? {
        if source is NSNull {
            return nil
        }
        return source.map { (source: AnyObject) -> T in
            Decoders.decode(clazz: clazz, source: source)
        }
    }

    static func decodeOptional<T>(clazz: [T].Type, source: AnyObject?) -> [T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }

    static func decodeOptional<T, Key: Hashable>(clazz: [Key:T].Type, source: AnyObject?) -> [Key:T]? {
        if source is NSNull {
            return nil
        }
        return source.map { (someSource: AnyObject) -> [Key:T] in
            Decoders.decode(clazz: clazz, source: someSource)
        }
    }

    private static var __once: () = {
        let formatters = [
            "yyyy-MM-dd",
            "yyyy-MM-dd'T'HH:mm:ssZZZZZ",
            "yyyy-MM-dd'T'HH:mm:ss.SSSZZZZZ",
            "yyyy-MM-dd'T'HH:mm:ss'Z'",
            "yyyy-MM-dd'T'HH:mm:ss.SSS",
            "yyyy-MM-dd HH:mm:ss"
        ].map { (format: String) -> DateFormatter in
            let formatter = DateFormatter()
            formatter.dateFormat = format
            return formatter
        }
        // Decoder for Date
        Decoders.addDecoder(clazz: Date.self) { (source: AnyObject) -> Date in
           if let sourceString = source as? String {
                for formatter in formatters {
                    if let date = formatter.date(from: sourceString) {
                        return date
                    }
                }
            }
            if let sourceInt = source as? Int64 {
                // treat as a java date
                return Date(timeIntervalSince1970: Double(sourceInt / 1000) )
            }
            fatalError("formatter failed to parse \(source)")
        } 

        // Decoder for [AddResponse]
        Decoders.addDecoder(clazz: [AddResponse].self) { (source: AnyObject) -> [AddResponse] in
            return Decoders.decode(clazz: [AddResponse].self, source: source)
        }
        // Decoder for AddResponse
        Decoders.addDecoder(clazz: AddResponse.self) { (source: AnyObject) -> AddResponse in
            let sourceDictionary = source as! [AnyHashable: Any]

            let instance = AddResponse()
            instance.responseTime = Decoders.decodeOptional(clazz: Int64.self, source: sourceDictionary["ResponseTime"] as AnyObject?)
            instance.response = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["Response"] as AnyObject?)
            instance.listItemId = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["ListItemId"] as AnyObject?)
            return instance
        }


        // Decoder for [Body]
        Decoders.addDecoder(clazz: [Body].self) { (source: AnyObject) -> [Body] in
            return Decoders.decode(clazz: [Body].self, source: source)
        }
        // Decoder for Body
        Decoders.addDecoder(clazz: Body.self) { (source: AnyObject) -> Body in
            let sourceDictionary = source as! [AnyHashable: Any]

            let instance = Body()
            instance.list = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["list"] as AnyObject?)
            instance.count = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["count"] as AnyObject?)
            instance.page = Decoders.decodeOptional(clazz: Int32.self, source: sourceDictionary["page"] as AnyObject?)
            instance.whereType = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["whereType"] as AnyObject?)
            instance._where = Decoders.decodeOptional(clazz: Array.self, source: sourceDictionary["where"] as AnyObject?)
            instance.order = Decoders.decodeOptional(clazz: ListOrder.self, source: sourceDictionary["order"] as AnyObject?)
            return instance
        }


        // Decoder for [ListOrder]
        Decoders.addDecoder(clazz: [ListOrder].self) { (source: AnyObject) -> [ListOrder] in
            return Decoders.decode(clazz: [ListOrder].self, source: source)
        }
        // Decoder for ListOrder
        Decoders.addDecoder(clazz: ListOrder.self) { (source: AnyObject) -> ListOrder in
            let sourceDictionary = source as! [AnyHashable: Any]

            let instance = ListOrder()
            instance.type = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["type"] as AnyObject?)
            instance.by = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["by"] as AnyObject?)
            return instance
        }


        // Decoder for [ModelError]
        Decoders.addDecoder(clazz: [ModelError].self) { (source: AnyObject) -> [ModelError] in
            return Decoders.decode(clazz: [ModelError].self, source: source)
        }
        // Decoder for ModelError
        Decoders.addDecoder(clazz: ModelError.self) { (source: AnyObject) -> ModelError in
            let sourceDictionary = source as! [AnyHashable: Any]

            let instance = ModelError()
            instance.responseTime = Decoders.decodeOptional(clazz: Int64.self, source: sourceDictionary["ResponseTime"] as AnyObject?)
            instance.response = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["Response"] as AnyObject?)
            instance.errorMessage = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["ErrorMessage"] as AnyObject?)
            return instance
        }


        // Decoder for [SetResponse]
        Decoders.addDecoder(clazz: [SetResponse].self) { (source: AnyObject) -> [SetResponse] in
            return Decoders.decode(clazz: [SetResponse].self, source: source)
        }
        // Decoder for SetResponse
        Decoders.addDecoder(clazz: SetResponse.self) { (source: AnyObject) -> SetResponse in
            let sourceDictionary = source as! [AnyHashable: Any]

            let instance = SetResponse()
            instance.responseTime = Decoders.decodeOptional(clazz: Int64.self, source: sourceDictionary["ResponseTime"] as AnyObject?)
            instance.response = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["Response"] as AnyObject?)
            return instance
        }


        // Decoder for [WhereItem]
        Decoders.addDecoder(clazz: [WhereItem].self) { (source: AnyObject) -> [WhereItem] in
            return Decoders.decode(clazz: [WhereItem].self, source: source)
        }
        // Decoder for WhereItem
        Decoders.addDecoder(clazz: WhereItem.self) { (source: AnyObject) -> WhereItem in
            let sourceDictionary = source as! [AnyHashable: Any]

            let instance = WhereItem()
            instance.type = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["type"] as AnyObject?)
            instance.column = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["column"] as AnyObject?)
            instance.value = Decoders.decodeOptional(clazz: String.self, source: sourceDictionary["value"] as AnyObject?)
            return instance
        }
    }()

    static fileprivate func initialize() {
        _ = Decoders.__once
    }
}
