//
// SetResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SetResponse: JSONEncodable {
    public var responseTime: Int64?
    public var response: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["ResponseTime"] = self.responseTime?.encodeToJSON()
        nillableDictionary["Response"] = self.response
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
